"""Add description to subscription_types

Revision ID: 7fc800bc6b64
Revises: 2ade16908291
Create Date: 2025-08-05 17:56:39.877197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fc800bc6b64'
down_revision: Union[str, Sequence[str], None] = '2ade16908291'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription_types', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription_types', 'description')
    # ### end Alembic commands ###
