"""Admin logic update

Revision ID: b54e4d726273
Revises: 7fc800bc6b64
Create Date: 2025-08-07 16:01:15.437579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b54e4d726273'
down_revision: Union[str, Sequence[str], None] = '7fc800bc6b64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('subscription_types_company_fkey'), 'subscription_types', type_='foreignkey')
    op.drop_column('subscription_types', 'company')
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'company_id')
    op.drop_column('users', 'is_admin')
    op.add_column('subscription_types', sa.Column('company', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('subscription_types_company_fkey'), 'subscription_types', 'companies', ['company'], ['id'])
    # ### end Alembic commands ###
